AWSTemplateFormatVersion: "2010-09-09"

Description: This template adds an EC2 instance to a vpc

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Exported VPC"
        Parameters: 
          - VpcStack3
    
      - Label:
          default: "EC2 Instance Parameters"
        Parameters: 
          - InstanceType
          - InstanceVolume
  
Parameters:
  VpcStack2:
    Description: The name of the vpc stack that exports values
    Type: String

  InstanceType:
    Type: String
    Description: It specifies the allowed and default instance type
    AllowedValues:
      - t1.micro
      - t2.micro
      - t3.micro
    Default: t2.micro

  AmazonImageId:
    Type: String
    Description: The Id of the Amazon Machine Image(AMI)

  KeyName:
    Type: 'AWS::EC2::KeyPair'
    Description: The key pair used for ssh access into the instance

Resources: 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Select [0, !GetAZs ""] 
      ImageId: !Ref AmazonImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - Fn::ImportValue: !Sub ${VpcStack3}-WebServersSecurityGroup
          SubnetId: 
            - Fn::ImportValue: !Sub ${VpcStack3}-PrivateSubnet1
      PrivateDnsNameOptions: 
          EnableResourceNameDnsARecord: True
      PrivateIpAddress: !GetAtt EC2Instance.DNSName
      SecurityGroups:
        - Fn::ImportValue: !Sub ${VpcStack3}-WebServersSecurityGroup
      SubnetId: 
        - Fn::ImportValue: !Sub ${VpcStack3}-PrivateSubnet1
      Tags: 
        - Key: Name
          Value: EC2-Instance
      Tenancy: default
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo su
            yum update -y
            yum install -y httpd
            systemctl start httpd.service
            echo "<h1> HELLO SERVER </h1>" > /var/www/html/index.html
  
Outputs:
  EC2Instance:
    Description: Instance Id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-InstanceId
  
